### ISSUE TITLE
jss package

### ISSUE THREAD

**Issue by csgillespie** [rjournal/rj#11]
Should we just extract the parts of the jss package we need and drop the dependency?

**Comment by mitchelloharawild** [comment]
I also thought that we don't use much from the jss package, and so it can probably be extracted easily. But agree that using it as a Remote is simple enough to keep the dependency.

**Comment by csgillespie** [comment]
I didn't know/realise that svn & remotes. Learn a new thing every day ;)

**Comment by mitchelloharawild** [comment]
I knew that you could set remotes for non-github repos, but had to do some searching to figure out how to use it with svn!
