### ISSUE TITLE
Problem with "Illegal byte sequence" in submission name

### ISSUE THREAD

**Issue by kaneplusplus** [rjournal/rj#20]
The improved `get_submission()` function is looking good. I did however run into an issue. The last time I tried I got the following error:

```{r}
ℹ Skipping 1rnyN29aGcxVedA-jwD3hMpHrnE-7pS7v.zip, it already exists
Error in extractor(file, exdir = dest) : cannot open file '/Users/mike/projects/r-journal/articles/Submissions/2020-140/Briz-Red�n/Briz-Red�n.pdf': No such file or directory
```

I believe the issue is the encoding of the name of the submission.

**Comment by kaneplusplus** [comment]
As a follow-up, it looks like we have lot synchronization between the articles directory and the google sheet. The last submission checked in was 2020-140.

Can I update the google doc manually?

**Comment by mitchelloharawild** [comment]
I can't reproduce this issue. Are you able to unzip this file manually?
